import { Inter } from "next/font/google";
import "./globals.css";
import ContextProvider from "../context.jsx/ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DevX AI",
  description: "Generated by next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
